### PR TITLE
Add libhwloc-dev for use with dma test in bist tool

### PR DESCRIPTION
**Pull request by buie1**
Need to add hwloc for use in the fpga_dma_test. 
Needed to get https://github.com/OPAE/opae-sdk/pull/317 to pass CI

### CODE REVIEW

**Comment by buie1** [comment]
Need code owner approval @OPAE/doc @OPAE/ci

**Comment by luebbers** [comment]
Please note that hwloc is currently not whitelisted - approval is pending.

**Comment by asgibbons** [comment]
Weird, as hwloc is a dependency of boost, which is whitelisted.

**Comment by buie1** [comment]
HWLOC is approved on the whitelist. Lets merge this please.
https://whitelisttool.amr.corp.intel.com/view.php?id=7280

**Pull request merged**
