### PR TITLE
Build samples

### PR DESCRIPTION
**Pull request by trixirt**
Depends on opae-libs pr
https://github.com/OPAE/opae-libs/pull/74

### CODE REVIEW

**Comment by tswhison** [comment]
@asgardkm Will these variable renames affect any of the CI jobs?

**Comment by asgardkm** [comment]
@tswhison no I don't believe so. Since the only CI script reference to `BUILD_ASE_SAMPLES` is in `scripts/cover-ase.sh`, and since it is also updated in this PR, any CI running this script should pick up the updated cmake `OPAE_BUILD_ASE_SAMPLES`variable.

**Comment by trixirt** [comment]
Moved the original opae-libs definition of the variables to samples/CMakeLists.txt

**Review by anandaravuri — APPROVED** [review]

**Comment by anandaravuri** [comment]
fixed in another PR

**Pull request closed without merging**
