### PR TITLE
c++core: rename get() fn to c_type()

### PR DESCRIPTION
**Pull request by r-rojo**
To avoid confusion and to better represent what this function does, it
is being renamed to `c_type()`
The plan is to also create a factory function for properties called
`get` which would be more in line with the OPAE C API
(`fpgaGetProperties`).

### CODE REVIEW

**Comment by michael-adler** [comment]
Why not c_handle()?

**Comment by michael-adler** [comment]
Never mind the previous comment if you saw it about c_handle(). I didn't read far enough to other types.

**Comment by r-rojo** [comment]
c_handle for every C++ type or c_handle for the handle class, and c_token for the token class, etc...?

**Comment by michael-adler** [comment]
@r-rojo please merge the change in intel-fpga-bbb (https://github.com/OPAE/intel-fpga-bbb/pull/23) when you merge this one. I put you on the review.

**Comment by r-rojo** [comment]
@tswhison , I don't know if I'd call this "hand holding". It's just a more explicit API for those that prefer it.

**Pull request merged**
