### PR TITLE
Fix passing param to fpgadiag in bist

### PR DESCRIPTION
**Pull request by buie1**
Resolving Issue: https://github.com/OPAE/opae-sdk/issues/1090

### CODE REVIEW

**Comment by dasm** [comment]
@buie1 can we merge this change?

**Comment by dasm** [comment]
@r-rojo @tswhison had to rebase due to other changes.

**Comment by dasm** [comment]
@r-rojo @tswhison can we get 👍 on this?

**Comment by dasm** [comment]
@tswhison @nakulkorde @r-rojo any idea whom should I ask for approval to get approval from "code owner"?

**Comment by tswhison** [comment]
Looks like tools needs to approve.  That would be @r-rojo or @anandaravuri.

**Pull request merged**
