### PR TITLE
Add fpgabist to get checked for coding style

### PR DESCRIPTION
**Pull request by buie1**
Format fpgabist C sources to comply with coding style

### CODE REVIEW

**Comment by southerngs** [comment]
@buie1 I also have some fixes for DMA code under review at: https://github.com/OPAE/opae-sdk/pull/228/commits/05081abace3cd593ffccd5dac27025f40fa037d3

We should make sure these get ported over to the AFU repo.

**Comment by buie1** [comment]
@southerngs Thanks for pointing this out Gabriel. Once you merge you changes I can handle the merge conflicts in this branch.  I wont want to merge this until I get the bist_afu app in main as well so I can knock out all the CI issues within the fpgabist too in one swoop.

**Comment by buie1** [comment]
@r-rojo @OPAE/ci 
Finally completed all the fixes to get the the fpgabist tool passing the coding style tests. Ready to get this merged so future changes can all conform to this standard.

**Comment by buie1** [comment]
@OPAE/ci @nakulkorde @rpSTTD 
Can we get this approved by you guys to get this merged in.

**Comment by buie1** [comment]
bitmoji

**Pull request merged**
