### PR TITLE
Enable building of opae-tests packages

### PR DESCRIPTION
**Pull request by dasm**
Added opae-tests.(deb|rpm) packages which are required for local testing
of OPAE SDK

### CODE REVIEW

**Comment by nakulkorde** [comment]
These changes look good, but since we are planning to branch out for opae 1.4 release this week, is it ok to put this PR on hold for a couple of days?

**Comment by dasm** [comment]
@nakulkorde probably would be nice to have this option included in next release. We're still week away from release.

**Comment by nakulkorde** [comment]
opae 1.4 is the public release of VC. It doesn't add any new features but only enables support for the upstream driver patch-set 2.

**Comment by dasm** [comment]
@nakulkorde if this PR looks good why would we need to wait another week before delivering? I'm required to do another update because my branch is out-of-date.
If this state would persist, then I would be required to update the very same branch approx. 10x

**Comment by nakulkorde** [comment]
@dasm I understand it is a pain to update the branch every so often. But the idea for this release is to avoid any changes unless required for the specific release. We expect to finish work for this release by tomorrow, once we branch out for the release then this can be merged into master.

Unless @rlee5-intel thinks it is ok to merge this in before we branch out for the release?

**Comment by rlee5-intel** [comment]
The next release 1.4.0 is a very targeted release.  We are branching out tomorrow morning and releasing next Monday.  I would recommend that we do not merge this change in 1.4.0 release.  Right after 1.4.0 we will start working on 1.4.1 immediately and we can pick up this change.  Thanks!

**Comment by nakulkorde** [comment]
We have branched out for the release and this can now go in.

**Pull request merged**
