### PR TITLE
Added new "sdl_test" folder inside tests folder inorder to test SDL requirements

### PR DESCRIPTION
**Pull request by vsivar1x**
Added new "sdl_test" folder inside samples directory inorder to test SDL requirements

### CODE REVIEW

**Comment by vsivar1x** [comment]
REVERIFY

**Comment by anandaravuri** [comment]
> REVERIFY


please add sdl test cases  to unit test folder,  add tests opea-libs/test  or opae-sdk/tests folder

**Review by tswhison — CHANGES_REQUESTED** [review]
I'm not sure we should be putting this in the public repo - SDL is an Intel internal policy.  Please consider placing in one of the internal repos.

**Comment by vsivar1x** [comment]
fpgaGetMetricsByName API depreciated. This is old product api. Not supported for new fpga cards. Unit test cases can be updated to implement SDL test cases. So, cancelled this code review.

**Pull request closed without merging**
