### PR TITLE
opae.admin: add error checking to supports_ecap

### PR DESCRIPTION
**Pull request by r-rojo**
Put the call to the subprocess in a try/except block and return False if
it fails.

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

### CODE REVIEW

**Review by tswhison — APPROVED** [review]

**Review by rchriste1 — COMMENTED** [review]
It seems the --force option still does not do the rsu function on a PC that does not support AER:
$ sudo rsu --force bmc
setpci: 0000:00:01.0: Extended capability 001d not found
setpci: 0000:00:01.0: Extended capability 0001 not found
2022-02-25 18:48:00,382 - ECAP_DPC and ECAP_AER not supported
2022-02-25 18:48:00,382 - RSU operation complete

On the Dell R740 server it now produces the result:
$ sudo rsu bmc
setpci: 0000:3a:00.0: Extended capability 001d not found
1d010001
2022-02-25 18:44:19,158 - [[pci_address(0000:3b:00.0), pci_id(0x1c2c, 0x1000)]] performing RSU operation
2022-02-25 18:44:19,160 - [[pci_address(0000:3a:00.0), pci_id(0x8086, 0x2030)]] removing device from PCIe bus
2022-02-25 18:44:19,263 - waiting 10 seconds for boot
2022-02-25 18:44:29,273 - rescanning PCIe bus: /sys/devices/pci0000:3a/pci_bus/0000:3a
2022-02-25 18:44:29,405 - RSU operation complete

**Review by anandaravuri — APPROVED** [review]

**Comment by r-rojo** [comment]
@rchriste1 , can you try again? I made a fix  that should fix this.

**Comment by rchriste1** [comment]
> The fix solves the problem when using --force. The output is now:
$ sudo rsu --force bmc
setpci: 0000:00:01.0: Extended capability 001d not found
2022-03-02 08:02:20,247 - [[pci_address(0000:01:00.0), pci_id(0x1c2c, 0x1000)]] performing RSU operation
2022-03-02 08:02:20,250 - [[pci_address(0000:00:01.0), pci_id(0x8086, 0x1901)]] removing device from PCIe bus
2022-03-02 08:02:20,301 - waiting 10 seconds for boot
2022-03-02 08:02:30,311 - rescanning PCIe bus: /sys/devices/pci0000:00/pci_bus/0000:00
2022-03-02 08:02:30,315 - RSU operation complete

BUT when running without --force, so nothing is done, rsu reports ok and returns 0:
$ sudo rsu bmc
setpci: 0000:00:01.0: Extended capability 001d not found
setpci: 0000:00:01.0: Extended capability 0001 not found
2022-03-02 08:01:18,930 - ECAP_DPC and ECAP_AER not supported
2022-03-02 08:01:18,930 - RSU operation complete

 I suggest you change the logging error in fpga.py to raise an IOError exception:
raise IOError('ECAP_DPC and ECAP_AER not supported')

**Review by rchriste1 — APPROVED** [review]
Thanks, now error message shows:
$ sudo rsu bmc
setpci: 0000:00:01.0: Extended capability 001d not found
setpci: 0000:00:01.0: Extended capability 0001 not found
2022-03-02 19:05:49,655 - ECAP_AER and ECAP_DPC not supported
2022-03-02 19:05:49,655 - RSU operation failed: ECAP_AER and ECAP_DPC not supported

**Pull request merged**
