### PR TITLE
c++: move headers to common dir

### PR DESCRIPTION
**Pull request by r-rojo**

### CODE REVIEW

**Comment by r-rojo** [comment]
I don't know... good question. opaecxx would be consistent but I was thinking about how it would look when you include something from there. 
```C++
#include <opae/enum.h>
#include <opaecxx/token.h>
```
vs.
```C++
#include <opae/enum.h>
#include <opaec++/token.h>
```

Or another idea is to put them in a sub-directory of opae. Which is what @luebbers and I had originally thought of. 
```C++
#include <opae/enum.h>
#include <opae/c++/token.h>
```

What is your opinion?

**Comment by tswhison** [comment]
I tend to gravitate towards opaecxx, because it would then match the guard sentinels if we were to move away from
* #pragma once
to
* #ifndef __OPAECXX_MYINCLUDE_H__

**Comment by r-rojo** [comment]
What about?
```C++
#include <opae/enum.h>
#include <opae/cxx/token.h>
```

**Comment by tswhison** [comment]
Yeah, I think that works, too.

**Pull request merged**
