### PR TITLE
tools: merge fpgabist from internal opae

### PR DESCRIPTION
**Pull request by anandaravuri**
- Merge Fpgabist, DMA tool code from internal Vista creek branch to master.
- Made changes changes to fpgabist + dma tool to support  Rush creek and Vista creek platform.
- Unifying fpgabist tool is not in  scope. of PR.

### CODE REVIEW

**Comment by buie1** [comment]
At first glance are these only cherry picks from the `master-x` branch?
If you need to keep DC functionality you will also need to check the `release/dcp-2.0` branch

**Comment by anandaravuri** [comment]
> At first glance are these only cherry picks from the `master-x` branch?
> If you need to keep DC functionality you will also need to check the `release/dcp-2.0` branch

Ananda: This PR Cherry-pick VC branch FPGABIST + DAM tools only.

**Comment by anandaravuri** [comment]
> This isn't strictly a cherry-pick, since the code is being modified. Let's only apply cherry-pick to the titles of pull requests that use the cherry-pick command exclusively.
> 
> Agree with Jon that this doesn't produce a unified fpgabist, but rather it puts the VC fpgabist on the external master. Is this what we want?

Ananda: Master FPGA BIST + VC fpgabist tool

**Comment by tswhison** [comment]
> > This isn't strictly a cherry-pick, since the code is being modified. Let's only apply cherry-pick to the titles of pull requests that use the cherry-pick command exclusively.
> > Agree with Jon that this doesn't produce a unified fpgabist, but rather it puts the VC fpgabist on the external master. Is this what we want?
> 
> Ananda: Master FPGA BIST + VC fpgabist tool

I don't know that fpgabist as it exists currently on external master is relevant.  Could you please follow up with Jon?  Two ARs here, 1) rename this pull request so that it doesn't mention cherry-pick and 2) decide on the plan for unifying fpgabist.  If a unified (release/dcp-2.0 + vista-creek) isn't within the scope of this pull request, then please file a Jira to capture the work.

**Comment by buie1** [comment]
> > > This isn't strictly a cherry-pick, since the code is being modified. Let's only apply cherry-pick to the titles of pull requests that use the cherry-pick command exclusively.
> > > Agree with Jon that this doesn't produce a unified fpgabist, but rather it puts the VC fpgabist on the external master. Is this what we want?
> > 
> > 
> > Ananda: Master FPGA BIST + VC fpgabist tool
> 
> I don't know that fpgabist as it exists currently on external master is relevant. Could you please follow up with Jon? Two ARs here, 1) rename this pull request so that it doesn't mention cherry-pick and 2) decide on the plan for unifying fpgabist. If a unified (release/dcp-2.0 + vista-creek) isn't within the scope of this pull request, then please file a Jira to capture the work.

We want to look at unifying fpgabist for the IOFS timeframe. I've started looking at scoping the work but no progress has or is planned to be made soon. The last AR is to verify that this PR keeps RC functionality as well as works on VC. @anandaravuri Can you provide test results?

**Pull request merged**
