### PR TITLE
user clk: read user clock dfh revision from uio driver

### PR DESCRIPTION
**Pull request by anandaravuri**
Signed-off-by: anandaravuri <ananda.ravuri@intel.com>

### CODE REVIEW

**Review by tswhison — APPROVED** [review]
LGTM.  What sort of testing was done?

**Review by michael-adler — APPROVED** [review]
Tested on Agilex and S10, confirmed both are detected and max. frequency matches the target. Loaded a GBS at 635 MHz on Agilex and the proper frequency was set.

Would it make sense to extend the CSRs to indicate properties of the clock so that you don't have to infer from the HW family?

**Review by michael-adler — APPROVED** [review]

**Comment by michael-adler** [comment]
@tswhison I think this is waiting on you as a code owner to approve. When I did a rebase in the GUI here it dropped your approval.

**Comment by tswhison** [comment]
Thanks @michael-adler.  I think that testing is still ongoing with this.

**Review by tswhison — APPROVED** [review]

**Pull request merged**
