### PR TITLE
docker: install kernel headers from elrepo

### PR DESCRIPTION
**Pull request by r-rojo**
Change docker file to:
* install elrepo and import its gpg key
* install kernel-ml-headers (mainline)

### CODE REVIEW

**Comment by r-rojo** [comment]
I ran the rpm build jobs using this branch and they passed:
https://github.com/OPAE/opae-sdk/actions/runs/321317938

**Comment by asgardkm** [comment]
@r-rojo is the addition of the el headers for pulling in the `vfio.h` headers for compilation?

I don't see a log difference between the CI build logs for this PR and prior PRs (such as https://github.com/OPAE/opae-sdk/runs/1288414341?check_suite_focus=true#step:6:205)

However, I think that the output string in CMake compilation (which would allow making this comparision) is being suppressed here:
https://github.com/OPAE/opae-sdk/blob/master/tools/extra/fpgadiag/CMakeLists.txt#L130

Where `else( SUPPORTS_VFIO)` should be `else()`

**Comment by r-rojo** [comment]
@asgardkm , yes. This is for building the vfio related libraries/applications (with the caveat being that this code will not work on older kernels because the data structures/constants are different).

This is for the CI jobs that build RPMs and run after a PR is merged into master. The CI jobs you mentioned shouldn't change.

The else syntax works either way in CMake.

**Review by tswhison — APPROVED** [review]
nice

**Review by asgardkm — APPROVED** [review]

**Pull request merged**
