### PR TITLE
Various updates for discrete platform

### PR DESCRIPTION
**Pull request by michael-adler**
- Stop building run.sh/clean.sh script wrappers in afu_synth_setup. They were a source of problems.
- Stop importing Stratix V HSSI/PCIe atoms in ASE. Not available on some platforms.

### CODE REVIEW

**Comment by michael-adler** [comment]
Regressions pass following the ASE Makefile update. It appears to have started failing with the update to 17.1.1.

http://sw-pert.altera.com/pert/pert.php?test_run_id=2166889

**Comment by michael-adler** [comment]
@abelardojarab: note change to ASE Makefile. Those attempted includes were failing after a Quartus change.

**Comment by deepakcu84** [comment]
Jake already removed stratixv atoms from ASE Makefile in a separate pull request in opae-sdk-x

https://github.intel.com/OPAE/opae-sdk-x/commit/8e16d8c2d6e320ad9da6071aa8f4f11a9ca90fda

You can submit yours. I think Makefile will need manual resolve when master-x syncs up with public.

**Comment by deepakcu84** [comment]
What about the failure in advanced_modelsim_questa? Does it appear related to this change

# ** Error: (vlib-35) Failed to create directory "/tmp/arc/668510774/_0/regtest/dcp_1.0-skx/ase/advanced_mem_model_questa/rtl_sim/work/work".
# File exists. (errno = EEXIST)
# ** Error: vlog failed.
# ** Error: subinvocation of vlog failed; return status = 1.
# ** Error: (vsim-3171) Could not find machine code for '/tmp/arc/668510774/_0/regtest/dcp_1.0-skx/ase/advanced_mem_model_questa/rtl_sim/work/work.ase_top'.
# No such file or directory. (errno = ENOENT)

**Comment by michael-adler** [comment]
Timeout waiting for a license.

**Pull request merged**
