### PR TITLE
userclk: Implement 10MHz to 600MHz range for iopll

### PR DESCRIPTION
**Pull request by rweight**
Change the table of configuration data for the IOPLL to implement
a range of 10MHz to 600MHz. Our method of limiting the 2x clock
will be to use the same frequency as the 1x clock when the 1x
frequency is above 300MHz.

Also remove a check that allows the high freq to be passed in as
zero.

Signed-off-by: Russ Weight <russell.h.weight@intel.com>

### CODE REVIEW

**Comment by michael-adler** [comment]
Please do figure out how to encode some PLL signature in the driver so we can continue to have a single clock control module for all products.

**Comment by rweight** [comment]
@anandaravuri: Can you please let me know if there is more required for this patch to be integrated?

**Comment by rweight** [comment]
I just rebased my patch on the latest code and re-pushed the branch. There were no conflicts.

**Comment by michael-adler** [comment]
@rweight  - for future reference, if you just click the update branch button on the GitHub web page for the pull request it will rebase and _will not_ require re-approval.

**Comment by rweight** [comment]
@michael-adler - I checked the master branch history and didn't see many merges, so I assumed that it was preferred to rebase the patch on the HEAD. I'm OK doing merges in the future.

**Comment by rweight** [comment]
@anandaravuri - can you approve again? I did a rebase instead of a merge, so the SHA changed and another approval is required. Note that there were no merge conflicts in the rebase.

**Comment by rweight** [comment]
@anandaravuri - can you please re-approve? I rebased the patch last week, and lost your approval in the process. There were not code conflicts.

**Pull request merged**
