### PR TITLE
Fix byteenable in the basic memory model

### PR DESCRIPTION
**Pull request by deepakcu84**
Signed-off-by: Deepak Unnikrishnan <deepak.unnikrishnan@intel.com>

### CODE REVIEW

**Comment by deepakcu84** [comment]
DMA test with address span extender (uses byteenables)

http://sj-pert.altera.com/pert/#do-not-bookmark-3

**Comment by deepakcu84** [comment]
ASE tests: http://sj-pert.altera.com/pert/pert.php?test_run_id=2195171

**Comment by deepakcu84** [comment]
OpenCL test failures are unrelated to this change

**Comment by michael-adler** [comment]
It was a bug and not a feature of the memory subsystem?

**Comment by deepakcu84** [comment]
That's correct. We discovered this bug when Chris switched his OpenCL to basic memory model. His test uses the address span expander which in turn uses byteenables. 

We never had a unit test case for byteenables w/ basic memory model. I plan to add a unit test in hello_mem_afu.

**Pull request merged**
