### PR TITLE
Prevent user from hurting himself

### PR DESCRIPTION
**Pull request by dasm**
Python has many ways of executing shell commands. By passing 'shell=True'
we've been exposing program for malicious behavior.
To prevent from doing that use built-in solution in Python [1] which helps
with blocking from shell injection.

[1] https://docs.python.org/2/library/subprocess.html#frequently-used-arguments

Signed-off-by: Dariusz Smigiel dariusz.smigiel@intel.com

### CODE REVIEW

**Comment by dasm** [comment]
@asgibbons I see errors not connected to my PR.
Let me fix them, create separate PR and after merging I'll update this PR.

**Comment by buie1** [comment]
@dasm I would try updating your branch before fixing whichever changes you were going to make addressing CI issues.

**Comment by dasm** [comment]
@asgibbons I've noticed that there was missing bracket which caused bunch of errors (good thing to have PEP8 check).
I've fixed that.

**Comment by dasm** [comment]
@buie1 yes, automated regression test was executed.

**Pull request merged**
