### PR TITLE
Check poll() return value in hello_events 

### PR DESCRIPTION
**Pull request by omkarhegde**
-Add integer variable to check return code of linux
    poll() call

### CODE REVIEW

**Comment by tswhison** [comment]
The CI failure looks like an internal error.  @r-rojo, could you have a look?

**Comment by southerngs** [comment]
@omkarhegde can you remove the reference to Klocwork in the commit message since we aren't using it on the public repo.  Just describe the problem that is being fixed instead.

**Comment by omkarhegde** [comment]
@southerngs  done.

**Comment by tswhison** [comment]
Talked to @r-rojo. We noticed that this failure is actually in the packager, which is strange since those files are not modified by this PR. It seems that there is a missing python dependency on 'jsonschema'. @rpSTTD, is this something you can help with?

**Comment by tswhison** [comment]
@omkarhegde you could try adding the following to .travis.yml, under the other pip install lines:

  - pip install --user jsonschema

**Pull request merged**
