### PR TITLE
Use a hash to track the wsid space.

### PR DESCRIPTION
**Pull request by michael-adler**
Unique workspace IDs are assigned to each allocated shared buffer. The IDs are used
for discovering the PA of a buffer and for passing the buffer size to the kernel when a page
is deallocated.  The data structure was a list, which didn't scale.  A million allocated
pages took over 1.5 hours to free.  The new code accomplishes the same in about 4 seconds.

### CODE REVIEW

**Comment by michael-adler** [comment]
@OPAE/api - I don't think the remaining Travis errors are mine. Is something wrong with the test system?

**Comment by michael-adler** [comment]
Tested using MPF's test_random torture test by allocating 1 million 4KB pages and then every second deallocating and reallocating a random number of pages. At the end, all pages are deallocated by walking the generated data structures. Failure to find a wsid would trigger an error.

**Comment by tswhison** [comment]
Neat implementation.  Could you please run a memory analysis, something like valgrind memcheck, before we check it in?

**Comment by michael-adler** [comment]
@tswhison good idea. Found one. Now it's clean:

==109681== 
==109681== HEAP SUMMARY:
==109681==     in use at exit: 0 bytes in 0 blocks
==109681==   total heap usage: 1,126 allocs, 1,126 frees, 714,773 bytes allocated
==109681== 
==109681== All heap blocks were freed -- no leaks are possible

**Pull request merged**
