### PR TITLE
add create & remove eth group to script

### PR DESCRIPTION
**Pull request by anandaravuri**

### CODE REVIEW

**Review by figozhang — APPROVED** [review]
it works on OPAE 2.0.

**Review by asgardkm — CHANGES_REQUESTED** [review]
This does not compile on redhat7.6 (rebased off latest master, where latest master does indeed compile)

```
[ 96%] Built target opae-c++-utils
Linking CXX shared module ../../../lib/eth_group.so
lto1: internal compiler error: in output_die, at dwarf2out.c:8500
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
lto-wrapper: /usr/bin/c++ returned 1 exit status
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [lib/eth_group.so] Error 1
make[1]: *** [tools/extra/fpgadiag/CMakeFiles/eth_group.dir/all] Error 2
```

**Comment by anandaravuri** [comment]
> This does not compile on redhat7.6 (rebased off latest master, where latest master does indeed compile)
> 
> ```
> [ 96%] Built target opae-c++-utils
> Linking CXX shared module ../../../lib/eth_group.so
> lto1: internal compiler error: in output_die, at dwarf2out.c:8500
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://bugzilla.redhat.com/bugzilla> for instructions.
> lto-wrapper: /usr/bin/c++ returned 1 exit status
> /usr/bin/ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> make[2]: *** [lib/eth_group.so] Error 1
> make[1]: *** [tools/extra/fpgadiag/CMakeFiles/eth_group.dir/all] Error 2
> ```

[Ananda] Merge PR with fix ( updated branch), you can try now

**Review by asgardkm — APPROVED** [review]
Thanks @anandaravuri . Confirmed builds on el7 after branch included `master`.

**Pull request merged**
