### PR TITLE
c++: apply coding style

### PR DESCRIPTION
**Pull request by r-rojo**
I used clang-format to modify all .h|.cpp files in the libopae++
codebase to apply google's coding style for C++.

_NOTE:_ Because this coding style uses two-space indentation instead of
the four that had been used before, this change will touch most code.

### CODE REVIEW

**Comment by tswhison** [comment]
I assume the tests are passing after the change?  Could you share a link to the clang-format you used and the command parameters one would pass to get the same result?

**Comment by r-rojo** [comment]
Yes, the tests pass with this change :)
I [downloaded](http://releases.llvm.org/download.html) and installed llvm+clang [binaries](http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz) on my dev machine to use clang-format. 
You can also use [cpplint.py](https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py) to check it.
It does complain about our TODOs missing author or bug id though.

**Comment by tswhison** [comment]
Are we not going to favor the #ifndef guards over #pragma once for headers?

**Comment by r-rojo** [comment]
clang-format didn't muck with the `#pragma once` and I'd rather use those. The only thing I configured for the clang-format config is to set `SortIncludes` to `false`.
You can see the config I used here:
https://gist.github.com/r-rojo/9b873fcd920ca627a87e770d776d865f

**Comment by southerngs** [comment]
do we have the coding style(s) we are using documented anywhere?

**Comment by r-rojo** [comment]
For C++, I've added the coding style to the documentation/proposal I've been working on. Currently, this documentation is part of the doc tree in feature/c++.
You can see it here:
https://github.com/OPAE/opae-sdk/blob/rrojo/c%2B%2Bdoc/doc/opae-c%2B%2B/opaecxx.md

**Comment by southerngs** [comment]
@r-rojo thanks for the link

**Pull request merged**
