### PR TITLE
merge branch feature/fpgadcfg to master

### PR DESCRIPTION
**Pull request by tswhison**

### CODE REVIEW

**Comment by jelonanX** [comment]
The pluginmgr_c_p.dummy_plugin test fails on hw. May want to mock only?

**Comment by tswhison** [comment]
Could you copy/paste the failing message?  I'll try to debug it.  skx-p?

**Comment by jelonanX** [comment]
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:461: Failure
      Expected: matches
      Which is: 105
To be equal to: 99
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 0
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 1
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:468: Failure
      Expected: fpgaOpen(t, &handles[i], i)
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 1
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
api-shell.c:187:fpgaClose() **ERROR** : wrapped_handle is NULL
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:473: Failure
      Expected: fpgaClose(handles[i++])
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:468: Failure
      Expected: fpgaOpen(t, &handles[i], i)
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 1
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
api-shell.c:187:fpgaClose() **ERROR** : wrapped_handle is NULL
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:473: Failure
      Expected: fpgaClose(handles[i++])
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:468: Failure
      Expected: fpgaOpen(t, &handles[i], i)
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 1
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
api-shell.c:187:fpgaClose() **ERROR** : wrapped_handle is NULL
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:473: Failure
      Expected: fpgaClose(handles[i++])
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:468: Failure
      Expected: fpgaOpen(t, &handles[i], i)
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:470: Failure
      Expected: fpgaReset(handles[i])
      Which is: 1
To be equal to: FPGA_NOT_SUPPORTED
      Which is: 6
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:472: Failure
Expected: (err.find(err_contains)) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
api-shell.c:187:fpgaClose() **ERROR** : wrapped_handle is NULL
/home/lab/workspace/jelonanx/opae-sdk/testing/opae-c/test_pluginmgr_c.cpp:473: Failure
      Expected: fpgaClose(handles[i++])
      Which is: 1
To be equal to: FPGA_OK
      Which is: 0
[  FAILED  ] pluginmgr_c_p.dummy_plugin (9 ms)
[----------] 1 test from pluginmgr_c_p (9 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] pluginmgr_c_p.dummy_plugin


I ran it on 37.

**Comment by tswhison** [comment]
@jelonanX, Thanks for the data.  It seems to also fail on master.  Let's not gate this pull based on that.  Will talk to @r-rojo about it tomorrow.

**Pull request merged**
