### PR TITLE
Lzhan55/ase refactor9

### PR DESCRIPTION
**Pull request by lzhan55**
- Removed unneeded code

### CODE REVIEW

**Comment by michael-adler** [comment]
Looks cleaner. What's the seed used for?

**Comment by lzhan55** [comment]
Seed is used for random number generation. We don't really need to save the seed in a file.

**Comment by michael-adler** [comment]
Right, I forgot. Last time I tried I couldn't get ASE to produce the same result from run to run. Perhaps I was setting the seed wrong. Does it work now if you force a seed, producing identical results each time?

**Comment by lzhan55** [comment]
The seed was either read from ase_config file, or randomly set based on the current time. If you set the seed in config file, it should be consistent.

**Pull request merged**
