### PR TITLE
Bump version number for next release branch

### PR DESCRIPTION
**Pull request by chipb**

### CODE REVIEW

**Comment by chipb** [comment]
Rationale: The default version for `master` should really not lag that of the most recent `release/*` branch.

**Comment by chipb** [comment]
*ahem* I guess I should pay attention to the contribution guide; I just added the S-o-B to the commit.

**Comment by shivarao** [comment]
@luebbers  what should the version on master be? It's currently 0.13.0, which is pretty out of date.

**Comment by luebbers** [comment]
Once we do a release, we should bump the version on master to reflect it (since all its changes should have been merged/cherry-picked into master). So that would make the current one 0.13.1 (which was released yesterday).

**Comment by shivarao** [comment]
@luebbers 0.14.0 was released yesterday. 0.13.1 was released last Wednesday.

So should it be 0.14.0?

**Comment by luebbers** [comment]
Yes - as soon as 0.14.0 pops up on GitHub, master should be updated to 0.14.0.

**Comment by chipb** [comment]
If that's our convention, here it is.

What branch do we integrate features into? There doesn't appear to be a 'develop' or 'integ' branch. If they go to master, it seems odd that "all stable fixes + new features" branch has a default version that always lags behind that of releases.

**Comment by luebbers** [comment]
New features should be developed on their own feature branch which will eventually merged into `master` before cutting a release that should contain that feature. The "git flow" model of a `develop` branch for integration and a `master` branch for stable releases doesn't really work for us because of the multiple parallel releases we have in flight - we tag release branches instead.

**Pull request merged**
