### PR TITLE
Break afu_platform_config into multiple modules

### PR DESCRIPTION
**Pull request by michael-adler**
- One module for loading JSON dbs
- One module for emitting configuration files
- Teach Python zipper to handle sources that are updated by CMake

### CODE REVIEW

**Comment by michael-adler** [comment]
No new behavior -- just significant refactoring. The module was getting way too big. The zipped image uses exactly the same CMake macro used by the packager.

Tests pass: http://sw-pert.altera.com/pert/pert.php?test_run_id=2174446

**Comment by abelardojarab** [comment]
Hi Michael, can you please add Tracy and I to the reviews?
This project involves several other users too.

**Comment by michael-adler** [comment]
@abelardojarab, no it isn't changing any arguments or semantics. It's just cleanup.

**Comment by michael-adler** [comment]
@abelardojarab, it says you requested changes, but I can't find them. Where?

**Pull request merged**
