### PR TITLE
packaging fix

### PR DESCRIPTION
**Pull request by hundeboll-silicom**
Fix the recent CI failure on centos7.6 -- see the last commit for details...

### CODE REVIEW

**Comment by trixirt** [comment]
Is the n5010 going to run on centos 7.6 ?

**Review by r-rojo — COMMENTED** [review]
Manually ran the job that builds the legacy RPMs and all three pass.

**Comment by hundeboll-silicom** [comment]
> Is the n5010 going to run on centos 7.6 ?

Not that I know of. But this is not specific to n5010.

**Comment by hundeboll-silicom** [comment]
Can we get a verdict on this?

**Review by anandaravuri — APPROVED** [review]

**Review by r-rojo — APPROVED** [review]

**Pull request merged**
